#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

#!/bin/bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80
sed -i 's/^\(listen .*\)80/\180/' /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

# Create a test index.html file
echo "Hello World!" > /var/www/html/index.html

